In [ ]:
#Numpy-Analyzer

In [3]:
## import numpy as np

class DataAnalytics:

    def __init__(self):
        self.arr = None

    # 1. ARRAY CREATION
    def create_array(self):
        print("\nSelect the type of array to create:")
        print("1. 1D Array")
        print("2. 2D Array")
        print("3. 3D Array")
        ch = int(input("Enter your choice: "))

        if ch == 1:
            size = int(input("Enter number of elements: "))
            data = list(map(int, input("Enter values separated by space: ").split()))
            self.arr = np.array(data)

        elif ch == 2:
            r = int(input("Enter number of rows: "))
            c = int(input("Enter number of columns: "))
            print(f"Enter {r*c} elements: ")
            data = list(map(int, input().split()))
            self.arr = np.array(data).reshape(r, c)

        elif ch == 3:
            x = int(input("Enter dimension 1: "))
            y = int(input("Enter dimension 2: "))
            z = int(input("Enter dimension 3: "))
            print(f"Enter {x*y*z} elements: ")
            data = list(map(int, input().split()))
            self.arr = np.array(data).reshape(x, y, z)

        print("\nArray created successfully:")
        print(self.arr)

    # 2. INDEXING & SLICING
    def indexing_slicing(self):
        print("\nChoose an operation:")
        print("1. Indexing")
        print("2. Slicing")
        print("3. Go Back")
        ch = int(input("Enter your choice: "))

        if ch == 1:
            i = int(input("Enter row index: "))
            j = int(input("Enter column index: "))
            print("\nElement:", self.arr[i][j])

        elif ch == 2:
            r = input("Enter row range (start:end): ")
            c = input("Enter column range (start:end): ")

            r1, r2 = map(int, r.split(":"))
            c1, c2 = map(int, c.split(":"))

            print("\nSliced Array:")
            print(self.arr[r1:r2, c1:c2])

    # 3. MATHEMATICAL OPERATIONS
    def math_operations(self):
        print("\nChoose a mathematical operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        ch = int(input("Enter your choice: "))

        print("\nEnter the same-size array elements:")
        data = list(map(int, input().split()))
        arr2 = np.array(data).reshape(self.arr.shape)

        print("\nOriginal Array:")
        print(self.arr)

        print("\nSecond Array:")
        print(arr2)

        if ch == 1:
            print("\nResult of Addition:")
            print(self.arr + arr2)
        elif ch == 2:
            print("\nResult of Subtraction:")
            print(self.arr - arr2)
        elif ch == 3:
            print("\nResult of Multiplication:")
            print(self.arr * arr2)
        elif ch == 4:
            print("\nResult of Division:")
            print(self.arr / arr2)

    # 4. COMBINE OR SPLIT ARRAYS
    def combine_split(self):
        print("\nChoose an option:")
        print("1. Combine Arrays")
        print("2. Split Array")
        ch = int(input("Enter your choice: "))

        if ch == 1:
            print("Enter elements of another array to combine:")
            data = list(map(int, input().split()))
            arr2 = np.array(data).reshape(self.arr.shape)

            print("\nOriginal Array:")
            print(self.arr)

            print("\nSecond Array:")
            print(arr2)

            print("\nCombined Array (Vertical Stack):")
            print(np.vstack((self.arr, arr2)))

        elif ch == 2:
            parts = int(input("How many parts to split? "))
            print("\nSplitted Arrays:")
            print(np.array_split(self.arr, parts))

    # 5. SEARCH / SORT / FILTER
    def search_sort_filter(self):
        print("\nChoose an option:")
        print("1. Search a value")
        print("2. Sort the array")
        print("3. Filter values")
        ch = int(input("Enter your choice: "))

        print("\nOriginal Array:")
        print(self.arr)

        if ch == 1:
            v = int(input("Enter value to search: "))
            print("Found at index:", np.where(self.arr == v))

        elif ch == 2:
            print("\nSorted Array:")
            print(np.sort(self.arr))
            print("(Sorting applied row-wise.)")

        elif ch == 3:
            v = int(input("Enter minimum value: "))
            print("\nFiltered Array:")
            print(self.arr[self.arr > v])

    # 6. AGGREGATES & STATISTICS
    def aggregates_stats(self):
        print("\nChoose an aggregate/statistical operation:")
        print("1. Sum")
        print("2. Mean")
        print("3. Median")
        print("4. Standard Deviation")
        print("5. Variance")
        ch = int(input("Enter your choice: "))

        print("\nOriginal Array:")
        print(self.arr)

        if ch == 1:
            print("\nSum of Array:", np.sum(self.arr))
        elif ch == 2:
            print("\nMean of Array:", np.mean(self.arr))
        elif ch == 3:
            print("\nMedian of Array:", np.median(self.arr))
        elif ch == 4:
            print("\nStandard Deviation:", np.std(self.arr))
        elif ch == 5:
            print("\nVariance:", np.var(self.arr))


# ---------------- MAIN MENU ----------------

obj = DataAnalytics()

print("Welcome to the NumPy Analyzer!")
print("================================")

while True:
    print("\nChoose an option:")
    print("1. Create a Numpy Array")
    print("2. Perform Mathematical Operations")
    print("3. Combine or Split Arrays")
    print("4. Search, Sort, or Filter Arrays")
    print("5. Compute Aggregates and Statistics")
    print("6. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        obj.create_array()
        obj.indexing_slicing()
    elif choice == 2:
        obj.math_operations()
    elif choice == 3:
        obj.combine_split()
    elif choice == 4:
        obj.search_sort_filter()
    elif choice == 5:
        obj.aggregates_stats()
    elif choice == 6:
        print("\nExiting...")
        break
    else:
        print("Invalid choice!")


Welcome to the NumPy Analyzer!

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  1



Select the type of array to create:
1. 1D Array
2. 2D Array
3. 3D Array


Enter your choice:  2
Enter number of rows:  3
Enter number of columns:  4


Enter 12 elements: 


 1 2 3 4 5 6 7 8 9 0 1 2



Array created successfully:
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]

Choose an operation:
1. Indexing
2. Slicing
3. Go Back


Enter your choice:  1
Enter row index:  2
Enter column index:  2



Element: 1

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  2



Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division


Enter your choice:  3



Enter the same-size array elements:


 5 5 5 5 5 5 4 5 6 7 8 3



Original Array:
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]

Second Array:
[[5 5 5 5]
 [5 5 4 5]
 [6 7 8 3]]

Result of Multiplication:
[[ 5 10 15 20]
 [25 30 28 40]
 [54  0  8  6]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  3



Choose an option:
1. Combine Arrays
2. Split Array


Enter your choice:  1


Enter elements of another array to combine:


 4 5 6 7 8 9 1 2 3 4 5 6



Original Array:
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]

Second Array:
[[4 5 6 7]
 [8 9 1 2]
 [3 4 5 6]]

Combined Array (Vertical Stack):
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]
 [4 5 6 7]
 [8 9 1 2]
 [3 4 5 6]]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  4



Choose an option:
1. Search a value
2. Sort the array
3. Filter values


Enter your choice:  2



Original Array:
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]

Sorted Array:
[[1 2 3 4]
 [5 6 7 8]
 [0 1 2 9]]
(Sorting applied row-wise.)

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  5



Choose an aggregate/statistical operation:
1. Sum
2. Mean
3. Median
4. Standard Deviation
5. Variance


Enter your choice:  1



Original Array:
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]

Sum of Array: 48

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  6



Exiting...
